project_id = "nzdljuvmyarxzxucybpg"

[functions.analyze-resume]
verify_jwt = false

[functions.invite-admin]
verify_jwt = false

[functions.upload-resume]
verify_jwt = false

[functions.get-resume-url]
verify_jwt = false
